# Generated by Django 2.1.5 on 2019-02-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200, unique=True)),
                ('game_mode', models.CharField(choices=[('osu!', 'osu'), ('osu!mania', 'osu!mania')], default='osu!', max_length=9)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
